line-length = 88
target-version = "py312"

[lint]
select = ["E", "W", "F", "I", "B", "UP", "ASYNC", "S", "SIM", "RUF"]
ignore = ["B008", "S101"]

[lint.isort]
known-first-party = ["src"]

[format]
quote-style = "double"
indent-style = "space"
